channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dependencies:
  - python==3.6
  - numpy
  - pip:
    - tensorflow==2.0.0-alpha0
    - ipykernel
    - numpy==1.15.4
    - scipy
    - scikit-learn
    - matplotlib
    - pandas
    - torch==1.0.0
    - torchvision==0.2.1





