dependencies:
  - python=3.6
  - pip:
    - tensorflow==2.0.0-alpha0
    - ipykernel
    - numpy==1.15.4
    - scipy
    - scikit-learn
    - matplotlib
    - pandas
    - https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl
    - torchvision
